- name: Commit results with PAT
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add odds.json
          git commit -m "update odds data" || echo "No changes to commit"
          git push https://${{ secrets.GH_PAT }}@github.com/okzarni/odds-scraper.git HEAD:main
